### ISSUE TITLE
i dont know how to solve this problem,please help me

### ISSUE THREAD

**Issue by jmp2xyy** [hunter-ht-2018/ptfuzzer#8]
sorry,i am poor at English...so i describe my problems briefly
platform:kali linux

these are my errors:

root@kali:~/ptfuzzer/build# sudo python ./bin/ptfuzzer.py "-i ./in_dir -o ./out_dir" "/usr/bin/pandoc -f docx -t html" 
Traceback (most recent call last):
  File "./bin/ptfuzzer.py", line 4, in <module>
    import cle
  File "/usr/local/lib/python2.7/dist-packages/cle/__init__.py", line 13, in <module>
    from .loader import *
  File "/usr/local/lib/python2.7/dist-packages/cle/loader.py", line 1000, in <module>
    from .backends import MetaELF, ELF, PE, Blob, ALL_BACKENDS, Backend
  File "/usr/local/lib/python2.7/dist-packages/cle/backends/__init__.py", line 322, in <module>
    from .elf import ELF, ELFCore, MetaELF
  File "/usr/local/lib/python2.7/dist-packages/cle/backends/elf/__init__.py", line 1, in <module>
    from .elf import ELF
  File "/usr/local/lib/python2.7/dist-packages/cle/backends/elf/elf.py", line 69
    raise CLECompatibilityError from e
                                   ^
SyntaxError: invalid syntax

**Comment by jmp2xyy** [comment]
it still seems problematic
![2018-10-03 02-35-10](https://user-images.githubusercontent.com/42863746/46387223-35469b00-c6b5-11e8-816a-9dd7cb864d68.png)

**Comment by ele7enxxh** [comment]
Hi, have you solved this problem yet?

**Comment by jmp2xyy** [comment]
> 嗨，你解决了这个问题吗？

not yet.

**Comment by zhanggenex** [comment]
I recall that PTfuzzer may not support testing pandoc because of some internel archietecture of pandoc. I also came to this problem when I was testing. @jmp2xyy @ele7enxxh

**Comment by jmp2xyy** [comment]
> I recall that PTfuzzer may not support testing pandoc because of some internel archietecture of pandoc. I also came to this problem when I was testing. @jmp2xyy @ele7enxxh

not support testing pandoc? I read this：https://www.freebuf.com/sectool/177578.html，it seems like to support testing pandoc
